// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC6Ucn1pBb1vTkGa-8SpBLa2QX8kWAAYg',
    appId: '1:369511478172:web:a6f5e58dee11d5c6940e59',
    messagingSenderId: '369511478172',
    projectId: 'pawguard-ai',
    authDomain: 'pawguard-ai.firebaseapp.com',
    storageBucket: 'pawguard-ai.firebasestorage.app',
    measurementId: 'G-E8NWW9QNRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkwEqtLJy1FhDnF56dTOhaHaFp_gmgq84',
    appId: '1:369511478172:android:7367d6a18d5b893f940e59',
    messagingSenderId: '369511478172',
    projectId: 'pawguard-ai',
    storageBucket: 'pawguard-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE8thw6ZeNbdX7VcYyJKHT4j5ov9UqwfQ',
    appId: '1:369511478172:ios:01045d2a7635e66c940e59',
    messagingSenderId: '369511478172',
    projectId: 'pawguard-ai',
    storageBucket: 'pawguard-ai.firebasestorage.app',
    iosBundleId: 'com.example.pawguardAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE8thw6ZeNbdX7VcYyJKHT4j5ov9UqwfQ',
    appId: '1:369511478172:ios:01045d2a7635e66c940e59',
    messagingSenderId: '369511478172',
    projectId: 'pawguard-ai',
    storageBucket: 'pawguard-ai.firebasestorage.app',
    iosBundleId: 'com.example.pawguardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC6Ucn1pBb1vTkGa-8SpBLa2QX8kWAAYg',
    appId: '1:369511478172:web:7a085567d4294f01940e59',
    messagingSenderId: '369511478172',
    projectId: 'pawguard-ai',
    authDomain: 'pawguard-ai.firebaseapp.com',
    storageBucket: 'pawguard-ai.firebasestorage.app',
    measurementId: 'G-737G8Y27G9',
  );

}